---
- name: Configure php-fpm socket listen user and group
  lineinfile:
    dest: "{{ php_fpm_pool_conf_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^listen\.owner.?=.+$', line: "listen.owner = {{ webserver_user }}" }
    - { regexp: '^listen\.group.?=.+$', line: "listen.group = {{ webserver_group }}" }
    - { regexp: '^listen\.mode.?=.+$', line: "listen.mode = 0660" }
  notify: restart php-fpm

# Give rights permissions to directories
- name: Ensure php working folder have the right group
  file:
      path: "{{ item }}"
      group: "{{ webserver_group }}"
      recurse: yes
      state: directory
  loop:
    - "{{ php_fpm_session_dir }}"
    - "{{ php_fpm_opcache_dir }}"
    - "{{ php_fpm_wsdlcache_dir }}"