---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-centos7-ansible:latest
    pre_build_image: True
    privileged: True
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 0.0.0.0:8080:80/tcp
      - 0.0.0.0:8443:443/tcp
provisioner:
  name: ansible
verifier:
  name: ansible
