---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 0.0.0.0:8080:80/tcp
      - 0.0.0.0:8443:443/tcp
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
